server:
  port: 88

opal:
  torrent:
    rss:
      cache.expire: 1000 # 5분
      site:
        tf.url: http://www.tfreeca22.com
        th.url: https://torrenthaja.com
        tw.url: https://torrentwal.com
        tb.url: https://torrentboza.net




